FROM public.ecr.aws/lambda/python:3.10

COPY ./app ${LAMBDA_TASK_ROOT}

RUN pip3 install -r requirements.txt -U --no-cache-dir

RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu

ENV HF_HOME	= /tmp/.cache/huggingface
ENV TRANSFORMERS_CACHE = /tmp/.cache/huggingface
ENV XDG_CACHE_HOME = /tmp/.cache

CMD ["main.handler"]